-- Multi-club foundation rollout
--
-- Goal:
-- - add the core club tables
-- - seed the current live club as the first club
-- - backfill existing shared data into that club
-- - keep current single-club app behavior working unchanged
--
-- Important:
-- - this rollout is intentionally backward-compatible
-- - current app code does not yet send club_id values
-- - compatibility triggers below keep new rows attached to the seeded live club
-- - access-control policy for the new multi-club tables is intentionally deferred
--   until the app starts reading/writing them in a club-aware way
--
-- What this migration enforces now:
-- - core relational integrity for memberships, preferences, and invite lineage
-- - provenance and mutation metadata needed for later administration
-- - a guardrail that prevents creating a second active standard club too early
--
-- What is intentionally deferred to later PRs:
-- - RLS and privilege policy for the new multi-club tables
-- - trusted app/database write paths for active club switching
-- - club-scoped read/write policy once the app starts using these tables
--
-- Proven live rollout order:
-- 1. create new tables
-- 2. add `club_id` columns to `book_club_list` and `schedule_changes`
-- 3. add indexes, updated_at helper triggers, and the single-standard-club guard
-- 4. seed the first live club plus `club_settings`, `club_memberships`, and `user_preferences`
-- 5. temporarily disable `trg_enforce_book_club_list_member_writes`
--    only for the `book_club_list.club_id` backfill, then re-enable it immediately
-- 6. backfill `schedule_changes.club_id`
-- 7. add compatibility triggers for future inserts
--
-- The temporary trigger bypass in step 5 was required because the existing
-- production admin-write guard treats the `club_id` backfill as a protected
-- update on `book_club_list`.

begin;

create table if not exists public.clubs (
    id bigint generated by default as identity primary key,
    name text not null,
    slug text not null unique,
    description text,
    club_type text not null default 'standard'
        check (club_type in ('standard', 'sandbox')),
    is_archived boolean not null default false,
    created_source text not null default 'user'
        check (created_source in ('seeded', 'user')),
    created_at timestamp with time zone not null default timezone('utc'::text, now()),
    updated_at timestamp with time zone not null default timezone('utc'::text, now()),
    archived_at timestamp with time zone,
    created_by uuid references public.user_profiles(id),
    archived_by uuid references public.user_profiles(id)
);

create table if not exists public.club_settings (
    club_id bigint primary key references public.clubs(id) on delete cascade,
    default_meeting_time text,
    default_timezone text,
    logo_url text,
    accent_color text,
    theme_token text,
    created_at timestamp with time zone not null default timezone('utc'::text, now()),
    updated_at timestamp with time zone not null default timezone('utc'::text, now()),
    updated_by uuid references public.user_profiles(id)
);

create table if not exists public.club_memberships (
    club_id bigint not null references public.clubs(id) on delete cascade,
    user_id uuid not null references public.user_profiles(id) on delete cascade,
    role text not null default 'member'
        check (role in ('member', 'admin')),
    status text not null default 'active'
        check (status in ('active', 'inactive')),
    membership_source text not null default 'invite'
        check (membership_source in ('seeded', 'invite', 'manual')),
    joined_at timestamp with time zone not null default timezone('utc'::text, now()),
    created_at timestamp with time zone not null default timezone('utc'::text, now()),
    updated_at timestamp with time zone not null default timezone('utc'::text, now()),
    ended_at timestamp with time zone,
    created_by uuid references public.user_profiles(id),
    invited_by uuid references public.user_profiles(id),
    ended_by uuid references public.user_profiles(id),
    unique (user_id, club_id),
    primary key (club_id, user_id)
);

create table if not exists public.platform_roles (
    user_id uuid primary key references public.user_profiles(id) on delete cascade,
    role text not null check (role in ('owner')),
    created_at timestamp with time zone not null default timezone('utc'::text, now()),
    created_by uuid references public.user_profiles(id)
);

create table if not exists public.club_invites (
    id bigint generated by default as identity primary key,
    club_id bigint not null references public.clubs(id) on delete cascade,
    code text not null unique,
    role_to_grant text not null default 'member'
        check (role_to_grant in ('member', 'admin')),
    valid_from timestamp with time zone,
    valid_until timestamp with time zone,
    max_uses integer,
    current_uses integer not null default 0,
    is_active boolean not null default true,
    revoked_at timestamp with time zone,
    revoked_by uuid references public.user_profiles(id),
    created_by uuid references public.user_profiles(id),
    created_at timestamp with time zone not null default timezone('utc'::text, now()),
    updated_at timestamp with time zone not null default timezone('utc'::text, now()),
    unique (id, club_id)
);

create table if not exists public.club_invite_consumptions (
    id bigint generated by default as identity primary key,
    club_id bigint not null references public.clubs(id) on delete cascade,
    invite_id bigint not null,
    user_id uuid not null references public.user_profiles(id) on delete cascade,
    consumed_at timestamp with time zone not null default timezone('utc'::text, now()),
    foreign key (invite_id, club_id)
        references public.club_invites(id, club_id)
        on delete cascade,
    unique (invite_id, user_id)
);

create table if not exists public.user_preferences (
    user_id uuid primary key references public.user_profiles(id) on delete cascade,
    active_club_id bigint,
    notification_preferences jsonb,
    visual_preferences jsonb,
    created_at timestamp with time zone not null default timezone('utc'::text, now()),
    updated_at timestamp with time zone not null default timezone('utc'::text, now()),
    foreign key (user_id, active_club_id)
        references public.club_memberships(user_id, club_id)
        deferrable initially deferred
);

alter table public.book_club_list
    add column if not exists club_id bigint references public.clubs(id);

alter table public.schedule_changes
    add column if not exists club_id bigint references public.clubs(id);

create index if not exists idx_book_club_list_club_id
    on public.book_club_list(club_id);

create index if not exists idx_book_club_list_club_id_status
    on public.book_club_list(club_id, status);

create index if not exists idx_schedule_changes_club_id_created_at
    on public.schedule_changes(club_id, created_at desc);

create index if not exists idx_club_memberships_user_id
    on public.club_memberships(user_id);

create index if not exists idx_club_invites_club_id
    on public.club_invites(club_id);

create index if not exists idx_club_invite_consumptions_user_id
    on public.club_invite_consumptions(user_id);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
    new.updated_at := timezone('utc'::text, now());
    return new;
end;
$$;

drop trigger if exists trg_touch_clubs_updated_at on public.clubs;
create trigger trg_touch_clubs_updated_at
    before update on public.clubs
    for each row
    execute function public.touch_updated_at();

drop trigger if exists trg_touch_club_settings_updated_at on public.club_settings;
create trigger trg_touch_club_settings_updated_at
    before update on public.club_settings
    for each row
    execute function public.touch_updated_at();

drop trigger if exists trg_touch_club_memberships_updated_at on public.club_memberships;
create trigger trg_touch_club_memberships_updated_at
    before update on public.club_memberships
    for each row
    execute function public.touch_updated_at();

drop trigger if exists trg_touch_club_invites_updated_at on public.club_invites;
create trigger trg_touch_club_invites_updated_at
    before update on public.club_invites
    for each row
    execute function public.touch_updated_at();

drop trigger if exists trg_touch_user_preferences_updated_at on public.user_preferences;
create trigger trg_touch_user_preferences_updated_at
    before update on public.user_preferences
    for each row
    execute function public.touch_updated_at();

create or replace function public.prevent_second_standard_club_before_club_scoping()
returns trigger
language plpgsql
set search_path = public
as $$
declare
    standard_club_count integer;
begin
    if new.club_type <> 'standard' then
        return new;
    end if;

    if tg_op = 'UPDATE'
       and old.club_type = 'standard'
       and old.is_archived = new.is_archived
       and old.slug = new.slug
       and old.id = new.id then
        return new;
    end if;

    select count(*)
    into standard_club_count
    from public.clubs
    where club_type = 'standard'
      and is_archived = false
      and (tg_op <> 'UPDATE' or id <> new.id);

    if standard_club_count >= 1 then
        raise exception
            'Cannot create a second active standard club until app writes are club-scoped.';
    end if;

    return new;
end;
$$;

drop trigger if exists trg_prevent_second_standard_club on public.clubs;
create trigger trg_prevent_second_standard_club
    before insert or update on public.clubs
    for each row
    when (new.is_archived = false)
    execute function public.prevent_second_standard_club_before_club_scoping();

create or replace function public.get_default_single_club_id()
returns bigint
language sql
stable
set search_path = public
as $$
    select id
    from public.clubs
    where is_archived = false
      and club_type = 'standard'
    order by created_at asc, id asc
    limit 1
$$;

with seeded_club as (
    insert into public.clubs (
        name,
        slug,
        description,
        club_type,
        created_source,
        created_by
    )
    values (
        'Book Club',
        'book-club',
        'Seeded live club created during multi-club foundation rollout',
        'standard',
        'seeded',
        null
    )
    on conflict (slug) do update
        set name = excluded.name
    returning id
),
resolved_club as (
    select id from seeded_club
    union all
    select c.id
    from public.clubs c
    where c.slug = 'book-club'
    limit 1
)
insert into public.club_settings (
    club_id,
    default_meeting_time,
    default_timezone,
    updated_by
)
select
    id,
    null,
    'America/New_York',
    null
from resolved_club
on conflict (club_id) do nothing;

with resolved_club as (
    select id
    from public.clubs
    where slug = 'book-club'
    limit 1
)
insert into public.club_memberships (
    club_id,
    user_id,
    role,
    status,
    membership_source,
    created_by,
    invited_by
)
select
    resolved_club.id,
    up.id,
    case when up.role = 'admin' then 'admin' else 'member' end,
    'active',
    'seeded',
    null,
    null
from public.user_profiles up
cross join resolved_club
on conflict (club_id, user_id) do update
    set role = excluded.role,
        status = excluded.status;

with resolved_club as (
    select id
    from public.clubs
    where slug = 'book-club'
    limit 1
)
insert into public.user_preferences (
    user_id,
    active_club_id
)
select
    up.id,
    resolved_club.id
from public.user_profiles up
cross join resolved_club
on conflict (user_id) do update
    set active_club_id = coalesce(public.user_preferences.active_club_id, excluded.active_club_id),
        updated_at = timezone('utc'::text, now());

alter table public.book_club_list
    disable trigger trg_enforce_book_club_list_member_writes;

with resolved_club as (
    select id
    from public.clubs
    where slug = 'book-club'
    limit 1
)
update public.book_club_list
set club_id = resolved_club.id
from resolved_club
where public.book_club_list.club_id is null;

alter table public.book_club_list
    enable trigger trg_enforce_book_club_list_member_writes;

with resolved_club as (
    select id
    from public.clubs
    where slug = 'book-club'
    limit 1
)
update public.schedule_changes
set club_id = resolved_club.id
from resolved_club
where public.schedule_changes.club_id is null;

create or replace function public.set_default_book_club_list_club_id()
returns trigger
language plpgsql
set search_path = public
as $$
begin
    if new.club_id is null then
        new.club_id := public.get_default_single_club_id();
    end if;
    return new;
end;
$$;

drop trigger if exists trg_set_default_book_club_list_club_id on public.book_club_list;

create trigger trg_set_default_book_club_list_club_id
    before insert on public.book_club_list
    for each row
    execute function public.set_default_book_club_list_club_id();

create or replace function public.set_default_schedule_changes_club_id()
returns trigger
language plpgsql
set search_path = public
as $$
begin
    if new.club_id is null and new.book_id is not null then
        select b.club_id
        into new.club_id
        from public.book_club_list b
        where b.id = new.book_id;
    end if;

    if new.club_id is null then
        new.club_id := public.get_default_single_club_id();
    end if;

    return new;
end;
$$;

drop trigger if exists trg_set_default_schedule_changes_club_id on public.schedule_changes;

create trigger trg_set_default_schedule_changes_club_id
    before insert on public.schedule_changes
    for each row
    execute function public.set_default_schedule_changes_club_id();

commit;
