-- Multi-club foundation rollout
--
-- Goal:
-- - add the core club tables
-- - seed the current live club as the first club
-- - backfill existing shared data into that club
-- - keep current single-club app behavior working unchanged
--
-- Important:
-- - this rollout is intentionally backward-compatible
-- - current app code does not yet send club_id values
-- - compatibility triggers below keep new rows attached to the seeded live club

begin;

create table if not exists public.clubs (
    id bigint generated by default as identity primary key,
    name text not null,
    slug text not null unique,
    description text,
    club_type text not null default 'standard'
        check (club_type in ('standard', 'sandbox')),
    is_archived boolean not null default false,
    created_at timestamp with time zone not null default timezone('utc'::text, now()),
    created_by uuid
);

create table if not exists public.club_settings (
    club_id bigint primary key references public.clubs(id) on delete cascade,
    default_meeting_time text,
    default_timezone text,
    logo_url text,
    accent_color text,
    theme_token text
);

create table if not exists public.club_memberships (
    club_id bigint not null references public.clubs(id) on delete cascade,
    user_id uuid not null references public.user_profiles(id) on delete cascade,
    role text not null default 'member'
        check (role in ('member', 'admin')),
    status text not null default 'active'
        check (status in ('active', 'inactive')),
    joined_at timestamp with time zone not null default timezone('utc'::text, now()),
    primary key (club_id, user_id)
);

create table if not exists public.platform_roles (
    user_id uuid primary key references public.user_profiles(id) on delete cascade,
    role text not null check (role in ('owner'))
);

create table if not exists public.club_invites (
    id bigint generated by default as identity primary key,
    club_id bigint not null references public.clubs(id) on delete cascade,
    code text not null unique,
    role_to_grant text not null default 'member'
        check (role_to_grant in ('member', 'admin')),
    valid_from timestamp with time zone,
    valid_until timestamp with time zone,
    max_uses integer,
    current_uses integer not null default 0,
    created_by uuid references public.user_profiles(id),
    created_at timestamp with time zone not null default timezone('utc'::text, now())
);

create table if not exists public.user_preferences (
    user_id uuid primary key references public.user_profiles(id) on delete cascade,
    active_club_id bigint references public.clubs(id),
    notification_preferences jsonb,
    visual_preferences jsonb,
    created_at timestamp with time zone not null default timezone('utc'::text, now()),
    updated_at timestamp with time zone not null default timezone('utc'::text, now())
);

alter table public.book_club_list
    add column if not exists club_id bigint references public.clubs(id);

alter table public.schedule_changes
    add column if not exists club_id bigint references public.clubs(id);

create index if not exists idx_book_club_list_club_id
    on public.book_club_list(club_id);

create index if not exists idx_book_club_list_club_id_status
    on public.book_club_list(club_id, status);

create index if not exists idx_schedule_changes_club_id_created_at
    on public.schedule_changes(club_id, created_at desc);

create index if not exists idx_club_memberships_user_id
    on public.club_memberships(user_id);

create or replace function public.get_default_single_club_id()
returns bigint
language sql
stable
set search_path = public
as $$
    select id
    from public.clubs
    where is_archived = false
      and club_type = 'standard'
    order by created_at asc, id asc
    limit 1
$$;

create or replace function public.set_default_book_club_list_club_id()
returns trigger
language plpgsql
set search_path = public
as $$
begin
    if new.club_id is null then
        new.club_id := public.get_default_single_club_id();
    end if;
    return new;
end;
$$;

drop trigger if exists trg_set_default_book_club_list_club_id on public.book_club_list;

create trigger trg_set_default_book_club_list_club_id
    before insert on public.book_club_list
    for each row
    execute function public.set_default_book_club_list_club_id();

create or replace function public.set_default_schedule_changes_club_id()
returns trigger
language plpgsql
set search_path = public
as $$
begin
    if new.club_id is null and new.book_id is not null then
        select b.club_id
        into new.club_id
        from public.book_club_list b
        where b.id = new.book_id;
    end if;

    if new.club_id is null then
        new.club_id := public.get_default_single_club_id();
    end if;

    return new;
end;
$$;

drop trigger if exists trg_set_default_schedule_changes_club_id on public.schedule_changes;

create trigger trg_set_default_schedule_changes_club_id
    before insert on public.schedule_changes
    for each row
    execute function public.set_default_schedule_changes_club_id();

with seeded_club as (
    insert into public.clubs (
        name,
        slug,
        description,
        club_type
    )
    values (
        'Book Club',
        'book-club',
        'Seeded live club created during multi-club foundation rollout',
        'standard'
    )
    on conflict (slug) do update
        set name = excluded.name
    returning id
),
resolved_club as (
    select id from seeded_club
    union all
    select c.id
    from public.clubs c
    where c.slug = 'book-club'
    limit 1
)
insert into public.club_settings (
    club_id,
    default_meeting_time,
    default_timezone
)
select
    id,
    null,
    'America/New_York'
from resolved_club
on conflict (club_id) do nothing;

with resolved_club as (
    select id
    from public.clubs
    where slug = 'book-club'
    limit 1
)
update public.book_club_list
set club_id = resolved_club.id
from resolved_club
where public.book_club_list.club_id is null;

with resolved_club as (
    select id
    from public.clubs
    where slug = 'book-club'
    limit 1
)
update public.schedule_changes
set club_id = resolved_club.id
from resolved_club
where public.schedule_changes.club_id is null;

with resolved_club as (
    select id
    from public.clubs
    where slug = 'book-club'
    limit 1
)
insert into public.club_memberships (
    club_id,
    user_id,
    role,
    status
)
select
    resolved_club.id,
    up.id,
    case when up.role = 'admin' then 'admin' else 'member' end,
    'active'
from public.user_profiles up
cross join resolved_club
on conflict (club_id, user_id) do update
    set role = excluded.role,
        status = excluded.status;

with resolved_club as (
    select id
    from public.clubs
    where slug = 'book-club'
    limit 1
)
insert into public.user_preferences (
    user_id,
    active_club_id
)
select
    up.id,
    resolved_club.id
from public.user_profiles up
cross join resolved_club
on conflict (user_id) do update
    set active_club_id = coalesce(public.user_preferences.active_club_id, excluded.active_club_id),
        updated_at = timezone('utc'::text, now());

commit;
