-- Consolidated application schema for Book Club Companion.
-- This file is intended to reflect the current app shape in the repository.
-- It includes the core tables, current status values, and the current
-- single-club permission model.

begin;

-- ---------------------------------------------------------------------------
-- User profiles
-- ---------------------------------------------------------------------------

create table if not exists public.user_profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    display_name text not null,
    role text not null default 'member'
        check (role in ('admin', 'member')),
    last_seen_at timestamp with time zone
);

comment on table public.user_profiles is 'Lightweight profile and role record for each auth user.';
comment on column public.user_profiles.role is 'Single-club role model. Multi-club support will likely replace this with memberships.';

alter table public.user_profiles enable row level security;

drop policy if exists "Authenticated users can read profiles" on public.user_profiles;
create policy "Authenticated users can read profiles"
    on public.user_profiles
    for select
    to authenticated
    using (true);

drop policy if exists "Users can create their own profile" on public.user_profiles;
create policy "Users can create their own profile"
    on public.user_profiles
    for insert
    to authenticated
    with check (auth.uid() = id);

drop policy if exists "Users can update their own profile" on public.user_profiles;
create policy "Users can update their own profile"
    on public.user_profiles
    for update
    to authenticated
    using (auth.uid() = id)
    with check (auth.uid() = id);

-- ---------------------------------------------------------------------------
-- Shared helper for role-aware policies and triggers
-- ---------------------------------------------------------------------------

create or replace function public.is_book_club_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.user_profiles
        where id = auth.uid()
          and role = 'admin'
    );
$$;

revoke all on function public.is_book_club_admin() from public;
grant execute on function public.is_book_club_admin() to authenticated;

-- ---------------------------------------------------------------------------
-- Core shared library
-- ---------------------------------------------------------------------------

create table if not exists public.book_club_list (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    title text not null,
    author text,
    google_data jsonb,
    status text not null default 'Saved'
        check (status in (
            'Saved',
            'Priority',
            'Possible',
            'Later',
            'Deprioritize',
            'Read',
            'Proposed',
            'Scheduled',
            'Test'
        )),
    rating numeric(3, 1) check (rating >= 0 and rating <= 5),
    rating_source text,
    rating_count integer,
    tags text[] default '{}'::text[],
    target_date date,
    meeting_time text,
    user_notes text,
    host_name text,
    discussion_questions text,
    proposed_by_user_id uuid references auth.users(id) on delete set null,
    last_modified_by uuid references auth.users(id) on delete set null,
    last_modified_at timestamp with time zone
);

comment on table public.book_club_list is 'Shared single-club reading list and meeting planner.';
comment on column public.book_club_list.status is 'Shared workflow state. Test is a temporary sandbox status until multi-club support exists.';
comment on column public.book_club_list.rating is 'Stored club-facing rating from Goodreads, Google Books, Open Library, or manual override.';
comment on column public.book_club_list.rating_source is 'Source of the stored rating: goodreads, googlebooks, openlibrary, or manual.';
comment on column public.book_club_list.rating_count is 'Approximate number of ratings from the chosen source.';
comment on column public.book_club_list.tags is 'Club tags used for browsing and discussion.';
comment on column public.book_club_list.meeting_time is 'Meeting time stored as app-friendly string (for example 19:15 or 19:15:00).';
comment on column public.book_club_list.discussion_questions is 'Shared official discussion guide text for the club.';
comment on column public.book_club_list.proposed_by_user_id is 'Auth user who originally proposed the book.';
comment on column public.book_club_list.last_modified_by is 'Auth user who last changed shared metadata.';

create index if not exists idx_book_club_list_status on public.book_club_list (status);
create index if not exists idx_book_club_list_target_date on public.book_club_list (target_date);
create index if not exists idx_book_club_list_created_at on public.book_club_list (created_at desc);

alter table public.book_club_list enable row level security;

drop policy if exists "Enable read access for authenticated users" on public.book_club_list;
create policy "Enable read access for authenticated users"
    on public.book_club_list
    for select
    to authenticated
    using (true);

drop policy if exists "Enable insert for authenticated users" on public.book_club_list;
create policy "Enable insert for authenticated users"
    on public.book_club_list
    for insert
    to authenticated
    with check (true);

drop policy if exists "Enable update for authenticated users" on public.book_club_list;
create policy "Enable update for authenticated users"
    on public.book_club_list
    for update
    to authenticated
    using (true)
    with check (true);

drop policy if exists "Enable delete for authenticated users" on public.book_club_list;
drop policy if exists "Enable delete for admins only" on public.book_club_list;
create policy "Enable delete for admins only"
    on public.book_club_list
    for delete
    to authenticated
    using (public.is_book_club_admin());

create or replace function public.enforce_book_club_list_member_writes()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    member_allowed_columns text[] := array[
        'host_name',
        'target_date',
        'meeting_time',
        'user_notes',
        'tags',
        'rating',
        'rating_source',
        'rating_count',
        'google_data',
        'last_modified_by',
        'last_modified_at'
    ];
begin
    if tg_op <> 'DELETE' and new.status is null then
        new.status := 'Saved';
    end if;

    if public.is_book_club_admin() then
        return case when tg_op = 'DELETE' then old else new end;
    end if;

    if tg_op = 'DELETE' then
        raise exception 'Only admins can delete books.';
    end if;

    if tg_op = 'INSERT' then
        if new.status <> 'Proposed' then
            raise exception 'Only admins can set a non-proposed book status during save.';
        end if;

        if coalesce(btrim(new.discussion_questions), '') <> '' then
            raise exception 'Only admins can create or overwrite the shared discussion guide.';
        end if;

        return new;
    end if;

    if new.google_data is distinct from old.google_data and old.google_data is not null then
        raise exception 'Only admins can replace stored book metadata.';
    end if;

    if (to_jsonb(new) - member_allowed_columns) is distinct from (to_jsonb(old) - member_allowed_columns) then
        raise exception 'Only admins can change shared workflow fields such as status, core book details, or discussion guides.';
    end if;

    return new;
end;
$$;

drop trigger if exists trg_enforce_book_club_list_member_writes on public.book_club_list;
create trigger trg_enforce_book_club_list_member_writes
    before insert or update or delete
    on public.book_club_list
    for each row
    execute function public.enforce_book_club_list_member_writes();

-- ---------------------------------------------------------------------------
-- Invite codes
-- ---------------------------------------------------------------------------

create table if not exists public.invite_codes (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    code text not null unique,
    valid_from timestamp with time zone,
    valid_until timestamp with time zone,
    max_uses integer,
    current_uses integer not null default 0
);

comment on table public.invite_codes is 'Current invite-only signup gate. This table is still client-driven and should eventually move behind a server-side RPC.';

-- Note: the current signup flow validates invite codes before authentication.
-- Because of that, the live app cannot yet use strict RLS on this table without
-- additional server-side work.

-- ---------------------------------------------------------------------------
-- Schedule change notifications
-- ---------------------------------------------------------------------------

create table if not exists public.schedule_changes (
    id bigint generated by default as identity primary key,
    book_id bigint references public.book_club_list(id) on delete cascade,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    book_title text not null,
    change_type text not null check (change_type in ('host', 'date', 'time')),
    old_value text,
    new_value text,
    changed_by_name text
);

create index if not exists idx_schedule_changes_created_at on public.schedule_changes (created_at desc);
create index if not exists idx_schedule_changes_book_id on public.schedule_changes (book_id);

alter table public.schedule_changes enable row level security;

drop policy if exists "Authenticated users can read schedule changes" on public.schedule_changes;
create policy "Authenticated users can read schedule changes"
    on public.schedule_changes
    for select
    to authenticated
    using (true);

drop policy if exists "Authenticated users can insert schedule changes" on public.schedule_changes;
create policy "Authenticated users can insert schedule changes"
    on public.schedule_changes
    for insert
    to authenticated
    with check (true);

-- ---------------------------------------------------------------------------
-- Per-user notification dismissals
-- ---------------------------------------------------------------------------

create table if not exists public.user_dismissed_notifications (
    user_id uuid not null references auth.users(id) on delete cascade,
    change_id bigint not null references public.schedule_changes(id) on delete cascade,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    primary key (user_id, change_id)
);

alter table public.user_dismissed_notifications enable row level security;

drop policy if exists "Users can read their dismissed notifications" on public.user_dismissed_notifications;
create policy "Users can read their dismissed notifications"
    on public.user_dismissed_notifications
    for select
    to authenticated
    using (auth.uid() = user_id);

drop policy if exists "Users can insert their dismissed notifications" on public.user_dismissed_notifications;
create policy "Users can insert their dismissed notifications"
    on public.user_dismissed_notifications
    for insert
    to authenticated
    with check (auth.uid() = user_id);

drop policy if exists "Users can update their dismissed notifications" on public.user_dismissed_notifications;
create policy "Users can update their dismissed notifications"
    on public.user_dismissed_notifications
    for update
    to authenticated
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

drop policy if exists "Users can delete their dismissed notifications" on public.user_dismissed_notifications;
create policy "Users can delete their dismissed notifications"
    on public.user_dismissed_notifications
    for delete
    to authenticated
    using (auth.uid() = user_id);

commit;
