-- Consolidated Schema for Book Club Companion

-- Create Table
CREATE TABLE IF NOT EXISTS book_club_list (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    title text NOT NULL,
    author text,
    google_data jsonb,
    status text CHECK (status IN ('Priority', 'Possible', 'Later', 'Deprioritize', 'Read', 'Proposed', 'Scheduled')),
    rating numeric(3, 1) CHECK (rating >= 0 AND rating <= 5),
    tags text[],
    target_date date,
    user_notes text,
    host_name text
);

-- Enable RLS
ALTER TABLE book_club_list ENABLE ROW LEVEL SECURITY;

-- Comments
COMMENT ON COLUMN book_club_list.rating IS 'User rating from 0 to 5 (supports decimals)';
COMMENT ON COLUMN book_club_list.status IS 'Reading status of the book';
COMMENT ON COLUMN book_club_list.tags IS 'Array of custom tags';
COMMENT ON COLUMN book_club_list.user_notes IS 'Personal notes or thoughts about the book';
COMMENT ON COLUMN book_club_list.club_year IS 'The year the book was read by the club (e.g. "2024")';
COMMENT ON COLUMN book_club_list.host_name IS 'The name of the host for this book';

-- RLS Policies
-- Note: These policies assume the table is shared among all authenticated users.
-- If user-specific data is needed, add a user_id column and update policies.

DROP POLICY IF EXISTS "Enable read access for authenticated users" ON book_club_list;
CREATE POLICY "Enable read access for authenticated users" ON book_club_list FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Enable insert for authenticated users" ON book_club_list;
CREATE POLICY "Enable insert for authenticated users" ON book_club_list FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Enable update for authenticated users" ON book_club_list;
CREATE POLICY "Enable update for authenticated users" ON book_club_list FOR UPDATE TO authenticated USING (true);

DROP POLICY IF EXISTS "Enable delete for authenticated users" ON book_club_list;
CREATE POLICY "Enable delete for authenticated users" ON book_club_list FOR DELETE TO authenticated USING (true);
